
title: Paulo Tada Resume
url: 'http://github.com/paulohtfs'


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Paulo Tada
tagline: Full Stack Developer
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: paulohtfs@gmail.com
website: github.com/paulohtfs
linkedin: paulo-tada-521329aa
github: paulohtfs
twitter: '@paulohtfs'

#Update all the sections by editing the files inside _includes folder.
