title: Paulo Tada
email: paulohtfs@gmail.com
description: >
  Software Developer CV for my carrer
baseurl: ""
url: ""
github_username: paulohtfs
#
# Build settings
#
sass:
  load_paths:
    - _sass
    - node_modules
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
